# -------
# Library
# -------

library:
  name: ComposeThemer
  api: 21
  github: MFlisar/ComposeThemer
  maven: io.github.mflisar.composethemer
  maven-main-library: core
  multiplatform: true
  platforms:
    - jvm
    - android
    - macos
    - ios
    - js
    - wasm
  screenshots: 
    - name: defaultpicker
      images:
        - ./screenshots/defaultpicker/android1.png
        - ./screenshots/defaultpicker/android2.png
        - ./screenshots/defaultpicker/android3.png
        - ./screenshots/defaultpicker/android4.png
        - ./screenshots/defaultpicker/desktop1.png
        - ./screenshots/defaultpicker/desktop2.png
        - ./screenshots/defaultpicker/desktop3.png
        - ./screenshots/defaultpicker/desktop4.png
        - ./screenshots/defaultpicker/desktop5.png
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.7.1 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.7.5 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.1 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: false

# ------------
# Groups
# ------------

groups:
  - name: core
    label: Core
    gradle-comment: core
  - name: modules
    label: Modules
    gradle-comment: modules
  - name: themes
    label: Themes
    gradle-comment: themes

# ------------
# Modules
# ------------

modules:
  - name: core
    group: core
    description: provides all the basic dialog classes to use and apply themes
    optional: false
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: modules-defaultpicker
    group: modules
    description: provides a default theme picker UI
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: modules-picker
    group: modules
    description: provides states and composables to create a theme picker UI
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: themes-flatui
    group: themes
    description: provides a list of themes based on the 20 flatui colors (each one in 5 variations)
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: themes-material500
    group: themes
    description: provides a list of themes based on the 20 material500 colors (each one in 5 variations)
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: themes-metro
    group: themes
    description: provides a list of themes based on the 20 metro colors (each one in 5 variations)
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []