# -------
# Library
# -------

library:
  name: ComposeThemer
  api: 21
  github: MFlisar/ComposeThemer
  maven: io.github.mflisar.composethemer
  maven-main-library: core
  multiplatform: true
  platforms:
    - jvm
    - android
    - macos
    - ios
    - js
    - wasm
  screenshots: 
    - name: core
      images:
        - ./screenshots/core/demo.gif
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.7.1 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.7.5 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.1 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: false

# ------------
# Groups
# ------------

groups:
  - name: core
    label: Core
    gradle-comment: core
  - name: modules
    label: Modules
    gradle-comment: modules
  - name: themes
    label: Themes
    gradle-comment: themes

# ------------
# Modules
# ------------

modules:
  - name: core
    group: core
    description: provides all the basic dialog classes to use and apply themes
    optional: false
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []
  - name: modules-picker
    group: modules
    description: provides extra modules for the core library
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: [ ]
  - name: themes-metro
    group: themes
    description: provides themes based on the 20 metro colors (including 5 variants per theme)
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
      - js
      - wasm
    platforms-info: ""
    dependencies: []