# -------
# Library
# -------

library:
  name: ComposeThemer
  api: 21
  github: MFlisar/ComposeThemer
  maven: io.github.mflisar.composethemer
  maven-main-library: core
  multiplatform: true
  screenshots:
    - name: Demo
      images:
        - ./screenshots/demo.gif
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

# optional
dependencies:
  compose:
    cmp: 1.7.1
    compose: 1.7.5
    material3: 1.3.1
    experimental: false

# -------------
# Module
# -------------

# GRUPPEN - optional: nur bei mehreren Modulen benötigt!
groups:
  - name: core
    label: Core
    gradle-comment: core 
  - name: modules
    label: Modules
    gradle-comment: modules

modules:
  - name: core
    group: core
    description: the core module
    optional: false
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: themes
    group: modules
    description: defines a set of 59 themes
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []